---

- name: create directory for mysqld exporter credentials
  file:
    path: "{{ prometheus_mysqld_exporter_mycnf_path | dirname }}"
    owner: root
    group: "{{ prometheus_exporters_common_group }}"
    mode: 0760
    state: directory

- name: save credentials for mysqld exporter
  copy:
    content: "{{ prometheus_mysqld_exporter_mycnf }}"
    dest: "{{ prometheus_mysqld_exporter_mycnf_path }}"
    owner: root
    group: "{{ prometheus_exporters_common_group }}"
    mode: 0640
  notify:
    - restart mysqld exporter

- name: download prometheus mysqld exporter binary
  get_url:
    url: "{{ prometheus_mysqld_exporter_url }}"
    dest: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_mysqld_exporter_release_name }}.tar.gz"

- name: unarchive binary tarball
  unarchive:
    copy: no
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_mysqld_exporter_release_name }}.tar.gz"
    dest: "{{ prometheus_exporters_common_dist_dir }}"
    creates: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_mysqld_exporter_release_name }}/mysqld_exporter"
  register: prometheus_mysqld_exporter_updated
  notify:
    - restart mysqld exporter

- name: update group and owner for files
  file:
    path: "{{ prometheus_mysqld_exporter_release_name }}"
    recurse: yes
    owner: "{{ prometheus_exporters_common_user }}"
    group: "{{ prometheus_exporters_common_group }}"
  when: prometheus_mysqld_exporter_updated | changed

- name: create symlink to the current release
  file:
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_mysqld_exporter_release_name }}"
    path: "{{ prometheus_exporters_common_root_dir }}/mysqld_exporter_current"
    state: link

- name: create systemd service unit
  template:
    src: etc/systemd/system/prometheus-mysqld-exporter.service.j2
    dest: /etc/systemd/system/prometheus-mysqld-exporter.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'
  notify:
    - reenable mysqld exporter service
    - restart mysqld exporter

- name: Looking which version of upstart is install
  command: initctl version
  when: ansible_service_mgr == 'upstart'
  register: upstart_version

- name: create init service unit
  template:
    src: etc/init/prometheus-mysqld-exporter.conf.j2
    dest: /etc/init/prometheus-mysqld-exporter.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'upstart'
  notify:
    - reinit mysqld exporter
    - restart mysqld exporter

- name: create sysvinit service unit
  template:
    src: etc/init.d/prometheus-mysqld-exporter.j2
    dest: /etc/init.d/prometheus-mysqld-exporter
    owner: root
    group: root
    mode: 0755
  when: ansible_service_mgr == 'sysvinit'
  notify:
    - restart mysqld exporter

- meta: flush_handlers

- name: ensure prometheus mysqld exporter service is enabled and started
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
