---

- name: reenable mysqld exporter service
  command: systemctl reenable prometheus-mysqld-exporter.service

- name: reinit mysqld exporter
  command: initctl reload-configuration

- name: restart mysqld exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted
